test:
    image: newser_bot
    container_name: bot_newser
    # restart: always
    volumes:
        - "/srv/logs/newser_server:/usr/src/app/data/logs"
    environment:
        - ANTICAPTCHA_ID=97203e301632af0a78ff1ba36390b902
        - SERVER_PORT=5000
        - SERVER_HOST=10.13.7.65
        - DEFAULT_PAGES=1
        - SERVER_SOURCE=server
        - LOCAL_FILE_SOURCE=file
        - WEB_APP_SOURCE=web
        - PUPPETEER_QUEUE=puppeteer_bot
        - UNPROCESSED_QUEUE=news_unprocessed
        - QUEUE_FILE=queries