test:
    image: newser_server
    container_name: server_newser
    restart: always
    volumes:
        - "/srv/logs/newser_server:/usr/src/app/data/logs"
    ports:
        - "4000:4000"
    environment:
        - QUERY_URL=http://10.19.19.4:1680/admin/give_search_query
        - RABBIT_HOST=10.19.19.4
        - RABBIT_PORT=5672
        - RABBIT_USER=admin
        - RABBIT_PASSWORD=admin
        - SERVER_PORT=4000